### ISSUE TITLE
ProjectInfoPage_Long does not work properly!

### ISSUE THREAD

**Issue by kenpham4real** [kenpham4real/socialject_alpha_1#37]
![image](https://user-images.githubusercontent.com/30412786/94126355-b50d3780-fe81-11ea-8674-cfc2eb8148ec.png)
@Chillisaucery I don't know what happended. Please take a look at this and resolve the issue

**Comment by Chillisaucery** [comment]
This is because the data on the Firebase doesn't legit. You have to click the project that has "recruit-info" and inside that have "benefits", "questions" and "requirements" as array. If the project doesn't have that, it will cause the project Info Page to crash.
It can work with 2 projects and doesn't with the other 2 right?
If the data on Firebase is structured correctly, this code will run correctly.

**Comment by TrNgTien** [comment]
it's happen again, I @Chillisaucery  found that is the problem of firebase

**Comment by kenpham4real** [comment]
Ok. Nice discovery. @Chillisaucery would love to have this issue pointed out earlier in the sprint.

**Comment by kenpham4real** [comment]
CLOSE THIS ISSUE SINCE LONG HAS RESOLVED IT WITH THE DEMO HE PROVIDED
@TrNgTien @Chillisaucery @HTD2k1
