### ISSUE TITLE
ProfilePage doesn't get fetched after create page 

### ISSUE THREAD

**Issue by kenpham4real** [kenpham4real/socialject_alpha_1#45]
### 1. Problem:
**The profile page of PPU has nothing after we create profile or PPU**
![image](https://user-images.githubusercontent.com/30412786/94451281-65f43900-01d8-11eb-8d3a-6abc1f63c2fa.png)

### 2. Suggested solution:
The problem can be in the action and the way data is rendered into UI in the component. They're not clear with bad naming and variables.

### Noticing that the data is fetched. However, the UI doesn't get rendered
![image](https://user-images.githubusercontent.com/30412786/94451444-99cf5e80-01d8-11eb-8ef7-7253b3271929.png)

**Comment by Chillisaucery** [comment]
Well now we have the same problem, just with different cause. As I remembered the previous cause was because of the typo mistake in the my code (it should have been orgId, instead I written orgID). I had fixed that, and now another problem emerges. The page still cannot fetch data, the reason I strongly believed that is from Firebase, as the field keys in the 'organization' collection doesn't match the keys in the code. Please fix the data keys, make it the same as that on Miro.
**Note** The key 'orgAvatar' somehow was changed into "imageFile" on Firebse, and it seems everyone else (except me) agreed to use it. So in the branch SPU-view-projects, I had written my code according to that key as well. If anyone wanted to change that, please tell me to fix my code as well, or if you want you can change that yourself.

**Comment by TrNgTien** [comment]
this problem is fix, i think becuz we have 1 event doesnt have anything
![Untitled](https://user-images.githubusercontent.com/66483590/94984117-e7e6b800-0572-11eb-973b-d2383e9d55ab.png)
and then if i choose another 
![Untitled](https://user-images.githubusercontent.com/66483590/94984127-ffbe3c00-0572-11eb-9dea-905a6c490751.png)

**Comment by TrNgTien** [comment]
hmmm when i created profile then i finish that but that's not fetched the image
![Untitled](https://user-images.githubusercontent.com/66483590/94984490-bc65cc80-0576-11eb-85b4-cf051290e7ac.png)

**Comment by TrNgTien** [comment]
![image](https://user-images.githubusercontent.com/66483590/94984610-f1beea00-0577-11eb-98ee-fcfae580626b.png)
i think this one make the button add a project in this one can't use
![image](https://user-images.githubusercontent.com/66483590/94984617-04d1ba00-0578-11eb-95fe-8159042eb1cd.png)

**Comment by TrNgTien** [comment]
@Chillisaucery plz check it

**Comment by Chillisaucery** [comment]
I fixed this

**Comment by kenpham4real** [comment]
**The other info is created successfully except for the avatar**
![image](https://user-images.githubusercontent.com/30412786/95041600-5f4a5200-0701-11eb-8c1e-4cde5125e280.png)
